name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'android/**'
      - '.github/workflows/build-debug-apk.yml'

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web app with debug features
        run: npm run build
        env:
          VITE_DEBUG_MODE: 'true'
          NODE_ENV: 'production'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android build tools
        run: |
          sdkmanager "build-tools;34.0.0"
          sdkmanager "platforms;android-34"

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Sign Debug APK
        run: |
          cd android/app/build/outputs/apk/debug
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../../../../debug.keystore -storepass android app-debug.apk androiddebugkey

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: neet-companion-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Show APK Info
        run: |
          echo "🐛 Debug APK Build Complete!"
          echo "📱 APK Location: android/app/build/outputs/apk/debug/app-debug.apk"
          echo "🔧 Debug Features Included:"
          echo "  - Console debug functions"
          echo "  - Visual debug panel at bottom"
          echo "  - Storage inspection tools"
          echo "  - Platform detection"
          echo ""
          echo "Console Commands Available:"
          echo "  window.debugInfo()     // Platform info"
          echo "  window.debugStorage()  // Storage inspection"
          echo "  window.testConfetti()  // Visual effects test"
          echo ""
          ls -la android/app/build/outputs/apk/debug/ || echo "APK directory not found"