name: Build Android APK

on:
  push:
    branches: [ main, App ]
  pull_request:
    branches: [ main, App ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install
      
    - name: Build web application (Normal Production)
      run: npm run build
      env:
        VITE_BUILD_VARIANT: 'normal'
        NODE_ENV: 'production'
      
    - name: Copy web assets to Android
      run: npx cap copy android
      
    - name: Sync Capacitor with Android
      run: npx cap sync android
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Generate debug keystore
      run: |
        cd android/app
        if [ ! -f debug.keystore ]; then
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        else
          echo "Debug keystore already exists, skipping generation"
        fi
    - name: Build Android APK (Release)
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: neet-companion-release-apk
        path: android/app/build/outputs/apk/release/*.apk
        
    - name: Show APK info
      run: |
        echo "✅ Android Production APK Build Complete!"
        echo "📱 Release APK files:"
        find android/app/build/outputs/apk/release/ -name "*.apk" -exec ls -la {} \;
        echo "💾 APK files are available in the Actions artifacts"
